### ISSUE TITLE
Rolling userId from Google

### ISSUE THREAD

**Issue by cumom** [jovotech/jovo-framework#390]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I expect the userId to be the same for each progressive request from the same user+device. Seems reasonable right?

## Current Behavior
The userId has "rolling" behavior (changes on each request from Google Assistant). The conversationId would at least be a bit more effective as a userId in this case, but Jovo appears to use the rolling userId to save the user state. We didn't used to have this problem. Is it possible that when we removed the location permission request caused this problem? Is there a way to specify the userId to be used when saving the user state to DynamoDB?

### Error log
1st request
```
        "user": {
          "locale": "en-US",
          "userId": "1550769073281877901588"
        },
        "conversation": {
          "conversationId": "1550769073281877901588",
          "type": "NEW"
        },
```
2nd request
```      
        "user": {
          "userStorage": "{\"userId\":\"1550769073281877901588\"}",
          "locale": "en-US",
          "userId": "15507690909882312946085"
        },
        "conversation": {
          "conversationId": "1550769073281877901588",
          "type": "ACTIVE",
          "conversationToken": "[\"session\"]"
        },
```        
3rd request    
```
        "user": {
          "userStorage": "{\"userId\":\"15507690909882312946085\"}",
          "locale": "en-US",
          "userId": "15507693541122490110481"
        },
        "conversation": {
          "conversationId": "1550769073281877901588",
          "type": "ACTIVE",
          "conversationToken": "[\"session\"]"
        }, 
```

## Your Environment

* Jovo Framework version used:
$jovo --version

Jovo CLI Version: 2.0.15

Jovo packages of current project:
  jovo-cli: 2.0.15
  jovo-cli-core: 2.0.10
  jovo-cli-deploy-lambda: 2.0.11
  jovo-cli-platform-alexa: 2.0.12
  jovo-cli-platform-google: 2.0.10
  jovo-cms-i18next: 2.0.14
  jovo-core: 2.0.14
  jovo-db-dynamodb: 2.0.15
  jovo-db-filedb: 2.0.15
  jovo-framework: 2.0.16
  jovo-platform-alexa: 2.0.19
  jovo-platform-dialogflow: 2.0.16
  jovo-platform-googleassistant: 2.0.18
  jovo-plugin-debugger: 2.0.15
  jovo-webhook-connector: 2.0.4

* Operating System:
Darwin imac5k.hsd1.in.comcast.net 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by jankoenig** [comment]
Hi @cumom, thanks! Yes, this makes sense. Google Assistant seems to change User IDs when it recognizes different voices or when voice match isn't enabled. If the incoming requests don't have `userStorage`, that's usually the problem. 

I agree that the `conversationId` can be used to double check if it's a new or returning user. We will think about a way to handle this.

Thank you,
Jan

**Comment by cumom** [comment]
I had to factory reset my device to get it back on my developer account last week. I'll check my voice match status.

**Comment by jankoenig** [comment]
OK, after looking at it in more detail, here are a few more thoughts:

User IDs for Google Actions are deprecated, and with Jovo `v2` we moved to webhook-generated user IDs saved in the user storage, as explained [in this official doc from Google](https://developers.google.com/actions/identity/user-info#migrating_to_webhook-generated_ids).

Our process for this is the following:
* If there is a `userId` defined in the `userStorage`, take this
* If not, use the `userId` from the request and then save it in `userStorage`
* If there is no `userId` in the request, generate one using `uuidv4`, and then save it to `userStorage`

You can find the code for this here: https://github.com/jovotech/jovo-framework/blob/43e9d4570e3d5eb7c0efe279a3fb424a13877692/jovo-integrations/jovo-platform-googleassistant/src/core/GoogleActionUser.ts#L31

So we can't really do anything about the `userId` coming in with the request, but we can make sure that it always uses the `userId` saved in `userStorage` for a consistent experience. 

You mentioned that it's not saving the state. Do you have the accompanying responses to the requests you mentioned above handy? Would be interesting to look at this. Are there also problems with saving things into a database?

**Comment by cumom** [comment]
Wahoo, voice match fixed it! I'll look more closely at the getId function. That process seems correct!

**Comment by jankoenig** [comment]
Great to hear that! We should still find a solution though, because not all users have voice match enabled

**Comment by cumom** [comment]
I did console.log('this.$storage:', this.$storage); at the beginning of getId() and got this with voice match off:

1st request
```
this.$storage: {}
this.$storage: { userId: '15507760748513711011698' }
...
        "user": {
          "locale": "en-US",
          "userId": "15507760748513711011698"
        },
        "conversation": {
          "conversationId": "15507760748513711011698",
          "type": "NEW"
        },
...
this.$storage: { userId: '15507760748513711011698' }
this.$storage: { userId: '15507760748513711011698' }

```
2nd request
```
this.$storage: {}
this.$storage: { userId: '15507760911793665687396' }
        "user": {
          "userStorage": "{\"userId\":\"15507760748513711011698\"}",
          "locale": "en-US",
          "userId": "15507760911793665687396"
        },
        "conversation": {
          "conversationId": "15507760748513711011698",
          "type": "ACTIVE",
          "conversationToken": "[\"session\"]"
        },
this.$storage: { userId: '15507760911793665687396' }
this.$storage: { userId: '15507760911793665687396' }
```

**Comment by jankoenig** [comment]
Thanks! There seems to be an issue accessing the `userStorage` from the request. Will investigate with @aswetlow

**Comment by cumom** [comment]
I got it to work with the following code in getId instead of the constructor:
        try {
            this.$storage = JSON.parse(_get(this.googleAction.$originalRequest || this.googleAction.$request, 'user.userStorage'));
        }
        catch (e) {
        }
I'm not sure if that is the right solution, but it works for me so far.

**Comment by jankoenig** [comment]
Thanks @cumom. This will be fixed with the next update

**Comment by aswetlow** [comment]
Fixed in 2.1

**Comment by StErMi** [comment]
Hi all, I still get the same problem. 
I'm using Jovo with this env

> Jovo CLI Version: 2.2.12
> 
> Jovo packages of current project:
>   jovo-cms-i18next: 2.2.14
>   jovo-core: 2.2.13
>   jovo-db-filedb: 2.2.13
>   jovo-db-mongodb: 2.2.14
>   jovo-framework: 2.2.16
>   jovo-platform-alexa: 2.2.18
>   jovo-platform-dialogflow: 2.2.14
>   jovo-platform-googleassistant: 2.2.16
>   jovo-plugin-debugger: 2.2.14

Every time I try to use this.$user.getId() I always get a different ID (even if in my MongoDB DB I see only 1 record for the user). What should I do?

**Comment by jankoenig** [comment]
Hey @StErMi, unfortunately, that's a known problem with Google. Have you tried testing on a phone? There's also a discussion going on here: https://community.jovo.tech/t/how-is-jovo-affected-by-deprecation-of-google-userid-request-field/547
