### ISSUE TITLE
Unable to run starting with framework v2.2.16 due to missing config defaults when using conversational components

### ISSUE THREAD

**Issue by stammbach** [jovotech/jovo-framework#598]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Issue

I've got a complex skill (wip) heavily relying on conversational components. After a small pause due to other projects I continued working on the skill and started with updating all jovo dependencies using the cli. Staring with version 2.2.16 I'm unable to run the project. Same goes for the provided component example from git.  

### Error log
```
  Message:
  Cannot read property 'config' of undefined
  
  Stack:
  TypeError: Cannot read property 'config' of undefined
      at new Component (<PROJECT_PATH>/node_modules/jovo-framework/src/middleware/Component.ts:13:25)
      at new ORDER_ADDRESS_FAVORITE (<PROJECT_PATH>/src/components/ORDER_ADDRESS_FAVORITE/index.js:5:5)
      at Object.<anonymous> (<PROJECT_PATH>/src/app.js:31:5)
      at Module._compile (internal/modules/cjs/loader.js:868:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
      at Module.load (internal/modules/cjs/loader.js:731:32)
      at Function.Module._load (internal/modules/cjs/loader.js:644:12)
      at Module.require (internal/modules/cjs/loader.js:771:19)
      at require (internal/modules/cjs/helpers.js:68:18)
      at Object.<anonymous> (<PROJECT_PATH>/src/index.js:4:17)
```

### Cause?
After some debugging I think its related due to the removal of the default constructor config on the base Component.

**2.2.15**
https://github.com/jovotech/jovo-framework/blob/b427c52a696f12646e01d52a530a80ccb29e1de0/jovo-framework/src/middleware/Component.ts#L7
**2.2.16+**
https://github.com/jovotech/jovo-framework/blob/aa937682c0d3dfd91bac737803a3d424e8447a31/jovo-framework/src/middleware/Component.ts#L6 

### Tried
If I try to manually provide an empty config inside the app like so:
```
app.useComponents(
    new ORDER_ADDRESS_FAVORITE({}), // <- Empty Config Object
    new ORDER_DELIVERY_ADDRESS({}),
    new ORDER_PAYMENT_METHOD({}),
);
```
Then the following error gets thrown:
```
 Message:
  Cannot read property 'bind' of undefined
  
  Stack:
  TypeError: Cannot read property 'bind' of undefined
      at <PROJECT_PATH>/node_modules/jovo-framework/src/App.ts:471:69
      at Array.forEach (<anonymous>)
      at App.useComponents (<PROJECT_PATH>/node_modules/jovo-framework/src/App.ts:470:14)
      at Object.<anonymous> (<PROJECT_PATH>/src/app.js:30:5)
      at Module._compile (internal/modules/cjs/loader.js:868:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
      at Module.load (internal/modules/cjs/loader.js:731:32)
      at Function.Module._load (internal/modules/cjs/loader.js:644:12)
      at Module.require (internal/modules/cjs/loader.js:771:19)
      at require (internal/modules/cjs/helpers.js:68:18)
```
Also adding component configs inside the main app config does not help.

## Your Environment

* Jovo Framework version used: 2.2.16+
* Operating System: macOS 10.14.6

**Comment by KaanKC** [comment]
Hi @stammbach ,

would you mind sharing the class definition of one of your components?

**Comment by stammbach** [comment]
@KaanKC if you run the PhoneNumber example you should get the same issue. At least in my experience. https://github.com/jovotech/jovo-framework/tree/master/examples/javascript/components

**Comment by KaanKC** [comment]
Ah yes, that's an outdated version.

We had to make some changes to the structure of components within the framework, so each incoming request (i.e. user) has its own set of component objects since they store request/user specific data.

One of those changes was that we renamed the base `Component` class to `ComponentPlugin`, so your issue should be fixed if your component class extends `ComponentPlugin` instead of `Component`.

```js
const {ComponentPlugin} = require('jovo-framework');

class PHONE_NUMBER extends ComponentPlugin {
    constructor(config) {
        super(config);
        this.handler = require('./src/handler');
        this.config = require('./src/config');
        this.pathToI18n = './src/i18n/';
    }
}

module.exports = PHONE_NUMBER;
```

That's one of the multiple changes made in that update. Another one, for example, is that the `components` folder was moved inside the `src` folder.

I'd recommend you to go through the [documentation](https://github.com/jovotech/jovo-framework/tree/master/docs/advanced-concepts/components) and compare it with your own components, as you will probably run into a couple more errors.

**Comment by stammbach** [comment]
Switching the base to `ComponentPlugin` did the trick. The only other impacting change was the updated `this.delegate` method.

I still don't get the "Component Scoped" Language Models, they absolutely make sense if you gonna share the component but in my experience they don't seem to get included when building the final model using the cli. Is that still WIP on the cli? 

Also sorry for the late response.

**Comment by KaanKC** [comment]
Yes, that's still WIP

**Comment by stammbach** [comment]
Oh okay, then I guess I have to keep my bloating model until its implemented :)

-> Closing as my main issue is resolved, thanks a lot.

**Comment by jankoenig** [comment]
Hey @stammbach, great to see you're already using Conversational Components :) We're very close to launching them, but it could still happen that we do changes here and there. The CLI update will also be published soon that builds all component models into the main language model

**Comment by stammbach** [comment]
@jankoenig, I really love them, I could not imagine how you should implement "complex" intents without using them. My intent requires 3 (for now, might become 4 eventually) user inputs, which all build upon each other, so its basically a "form like" implementation where I have one component for each input which then has its own validation and guidance. After providing and confirming the input he then will be delegated to the next input, or back if the user wants to change the input. In the end I send all inputs to the final intent which otherwise would require a not-user-friendly sentence to function. 

The only thing I had to implement myself were methods for sending the component response, which is now included, and some react-like "state" (component session data) usage helpers.

**Comment by stammbach** [comment]
I am @jankoenig, but currently I need to focus on finishing all related projects, because it's building upon an also wip system which provides the account linking functionality for this skill. I also just recently dumped the "micro-components" in favour of using one component with many nested states, because they are too connected to each other to split them up into individual components. (#609 really helps with that :P)

But once we're done I will get back to that offer, I promise!
